/**
 * Property-Based Tests for Itinerary Persistence
 *
 * Feature: tripai-travel-planner
 * Property 22: Itinerary Database Persistence
 * Property 23: Itinerary Save-Load Round-trip
 * Property 24: Itinerary Deletion
 *
 * Validates: Requirements 10.1, 10.3, 10.4
 */

import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import * as fc from "fast-check";
import {
  saveItinerary,
  loadItinerary,
  deleteItinerary,
  listUserItineraries,
  getItineraryCount,
  FreeTierLimitError,
  ItineraryNotFoundError,
} from "@/lib/supabase/itineraries";
import { supabase } from "@/lib/supabase/client";
import type { Itinerary } from "@/types/itinerary";
import { itineraryArbitrary } from "@/test/utils/property-test-helpers";

// Mock Supabase client
vi.mock("@/lib/supabase/client", () => ({
  supabase: {
    from: vi.fn(),
    auth: {
      getUser: vi.fn(),
      getSession: vi.fn(),
    },
  },
}));

describe("Property 22: Itinerary Database Persistence", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  // Feature: tripai-travel-planner, Property 22: Itinerary Database Persistence
  it("should store any itinerary in the database linked to user ID", async () => {
    await fc.assert(
      fc.asyncProperty(itineraryArbitrary, async (itinerary) => {
        // Remove fields that are generated by the database
        const { id, created_at, updated_at, ...itineraryToSave } = itinerary;

        // Mock successful save
        const savedItinerary: Itinerary = {
          ...itineraryToSave,
          id: fc.sample(fc.uuid(), 1)[0],
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        };

        const mockFrom = vi.fn(() => ({
          insert: vi.fn().mockReturnThis(),
          select: vi.fn().mockReturnThis(),
          single: vi.fn().mockResolvedValue({
            data: {
              id: savedItinerary.id,
              user_id: savedItinerary.user_id,
              title: savedItinerary.title,
              destination: savedItinerary.destination,
              start_date: savedItinerary.start_date,
              end_date: savedItinerary.end_date,
              data: {
                days: savedItinerary.days,
                shared_with: savedItinerary.shared_with,
              },
              created_at: savedItinerary.created_at,
              updated_at: savedItinerary.updated_at,
            },
            error: null,
          }),
        }));

        vi.mocked(supabase.from).mockImplementation(mockFrom as any);

        // Save the itinerary
        const result = await saveItinerary(itineraryToSave);

        // Verify it was saved with correct data
        expect(result.user_id).toBe(itineraryToSave.user_id);
        expect(result.title).toBe(itineraryToSave.title);
        expect(result.destination).toBe(itineraryToSave.destination);
        expect(result.start_date).toBe(itineraryToSave.start_date);
        expect(result.end_date).toBe(itineraryToSave.end_date);
        expect(result.days).toEqual(itineraryToSave.days);
        expect(result.shared_with).toEqual(itineraryToSave.shared_with);

        // Verify generated fields exist
        expect(result.id).toBeDefined();
        expect(result.created_at).toBeDefined();
        expect(result.updated_at).toBeDefined();

        // Verify database was called
        expect(supabase.from).toHaveBeenCalledWith("itineraries");
      }),
      { numRuns: 100 }
    );
  });

  // Feature: tripai-travel-planner, Property 22: Itinerary Database Persistence
  it("should retrieve saved itinerary by ID", async () => {
    await fc.assert(
      fc.asyncProperty(itineraryArbitrary, async (itinerary) => {
        // Mock successful load
        const mockFrom = vi.fn(() => ({
          select: vi.fn().mockReturnThis(),
          eq: vi.fn().mockReturnThis(),
          single: vi.fn().mockResolvedValue({
            data: {
              id: itinerary.id,
              user_id: itinerary.user_id,
              title: itinerary.title,
              destination: itinerary.destination,
              start_date: itinerary.start_date,
              end_date: itinerary.end_date,
              data: {
                days: itinerary.days,
                shared_with: itinerary.shared_with,
              },
              created_at: itinerary.created_at,
              updated_at: itinerary.updated_at,
            },
            error: null,
          }),
        }));

        vi.mocked(supabase.from).mockImplementation(mockFrom as any);

        // Load the itinerary
        const result = await loadItinerary(itinerary.id);

        // Verify all data is retrieved
        expect(result.id).toBe(itinerary.id);
        expect(result.user_id).toBe(itinerary.user_id);
        expect(result.title).toBe(itinerary.title);
        expect(result.destination).toBe(itinerary.destination);
        expect(result.start_date).toBe(itinerary.start_date);
        expect(result.end_date).toBe(itinerary.end_date);
        expect(result.days).toEqual(itinerary.days);
        expect(result.shared_with).toEqual(itinerary.shared_with);
        expect(result.created_at).toBe(itinerary.created_at);
        expect(result.updated_at).toBe(itinerary.updated_at);

        // Verify database was called with correct ID
        expect(supabase.from).toHaveBeenCalledWith("itineraries");
      }),
      { numRuns: 100 }
    );
  });

  // Feature: tripai-travel-planner, Property 22: Itinerary Database Persistence
  it("should throw FreeTierLimitError when user has 3 itineraries", async () => {
    await fc.assert(
      fc.asyncProperty(itineraryArbitrary, async (itinerary) => {
        const { id, created_at, updated_at, ...itineraryToSave } = itinerary;

        // Mock free tier limit error
        const mockFrom = vi.fn(() => ({
          insert: vi.fn().mockReturnThis(),
          select: vi.fn().mockReturnThis(),
          single: vi.fn().mockResolvedValue({
            data: null,
            error: {
              message: "Free tier users can only create 3 itineraries",
              code: "23514",
            },
          }),
        }));

        vi.mocked(supabase.from).mockImplementation(mockFrom as any);

        // Attempt to save should throw
        await expect(saveItinerary(itineraryToSave)).rejects.toThrow(
          FreeTierLimitError
        );
      }),
      { numRuns: 100 }
    );
  });

  // Feature: tripai-travel-planner, Property 22: Itinerary Database Persistence
  it("should throw ItineraryNotFoundError when loading non-existent itinerary", async () => {
    await fc.assert(
      fc.asyncProperty(fc.uuid(), async (nonExistentId) => {
        // Mock not found error
        const mockFrom = vi.fn(() => ({
          select: vi.fn().mockReturnThis(),
          eq: vi.fn().mockReturnThis(),
          single: vi.fn().mockResolvedValue({
            data: null,
            error: {
              message: "No rows found",
              code: "PGRST116",
            },
          }),
        }));

        vi.mocked(supabase.from).mockImplementation(mockFrom as any);

        // Attempt to load should throw
        await expect(loadItinerary(nonExistentId)).rejects.toThrow(
          ItineraryNotFoundError
        );
      }),
      { numRuns: 100 }
    );
  });
});

describe("Property 23: Itinerary Save-Load Round-trip", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  // Feature: tripai-travel-planner, Property 23: Itinerary Save-Load Round-trip
  it("should preserve all data in save-load round-trip", async () => {
    await fc.assert(
      fc.asyncProperty(itineraryArbitrary, async (originalItinerary) => {
        const { id, created_at, updated_at, ...itineraryToSave } =
          originalItinerary;

        // Generate IDs and timestamps for saved version
        const savedId = fc.sample(fc.uuid(), 1)[0];
        const savedCreatedAt = new Date().toISOString();
        const savedUpdatedAt = new Date().toISOString();

        // Mock save operation
        const mockSaveFrom = vi.fn(() => ({
          insert: vi.fn().mockReturnThis(),
          select: vi.fn().mockReturnThis(),
          single: vi.fn().mockResolvedValue({
            data: {
              id: savedId,
              user_id: itineraryToSave.user_id,
              title: itineraryToSave.title,
              destination: itineraryToSave.destination,
              start_date: itineraryToSave.start_date,
              end_date: itineraryToSave.end_date,
              data: {
                days: itineraryToSave.days,
                shared_with: itineraryToSave.shared_with,
              },
              created_at: savedCreatedAt,
              updated_at: savedUpdatedAt,
            },
            error: null,
          }),
        }));

        vi.mocked(supabase.from).mockImplementation(mockSaveFrom as any);

        // Save the itinerary
        const saved = await saveItinerary(itineraryToSave);

        // Mock load operation
        const mockLoadFrom = vi.fn(() => ({
          select: vi.fn().mockReturnThis(),
          eq: vi.fn().mockReturnThis(),
          single: vi.fn().mockResolvedValue({
            data: {
              id: saved.id,
              user_id: saved.user_id,
              title: saved.title,
              destination: saved.destination,
              start_date: saved.start_date,
              end_date: saved.end_date,
              data: {
                days: saved.days,
                shared_with: saved.shared_with,
              },
              created_at: saved.created_at,
              updated_at: saved.updated_at,
            },
            error: null,
          }),
        }));

        vi.mocked(supabase.from).mockImplementation(mockLoadFrom as any);

        // Load the itinerary
        const loaded = await loadItinerary(saved.id);

        // Verify round-trip preserves all data
        expect(loaded.id).toBe(saved.id);
        expect(loaded.user_id).toBe(itineraryToSave.user_id);
        expect(loaded.title).toBe(itineraryToSave.title);
        expect(loaded.destination).toBe(itineraryToSave.destination);
        expect(loaded.start_date).toBe(itineraryToSave.start_date);
        expect(loaded.end_date).toBe(itineraryToSave.end_date);
        expect(loaded.days).toEqual(itineraryToSave.days);
        expect(loaded.shared_with).toEqual(itineraryToSave.shared_with);
        expect(loaded.created_at).toBe(saved.created_at);
        expect(loaded.updated_at).toBe(saved.updated_at);

        // Verify structure is preserved
        expect(loaded.days.length).toBe(itineraryToSave.days.length);
        loaded.days.forEach((day, i) => {
          expect(day.day_number).toBe(itineraryToSave.days[i].day_number);
          expect(day.date).toBe(itineraryToSave.days[i].date);
          expect(day.activities.length).toBe(
            itineraryToSave.days[i].activities.length
          );

          day.activities.forEach((activity, j) => {
            const originalActivity = itineraryToSave.days[i].activities[j];
            expect(activity.id).toBe(originalActivity.id);
            expect(activity.time).toBe(originalActivity.time);
            expect(activity.title).toBe(originalActivity.title);
            expect(activity.description).toBe(originalActivity.description);
            expect(activity.location).toEqual(originalActivity.location);
            expect(activity.duration_minutes).toBe(
              originalActivity.duration_minutes
            );
            expect(activity.order).toBe(originalActivity.order);
          });
        });
      }),
      { numRuns: 100 }
    );
  });

  // Feature: tripai-travel-planner, Property 23: Itinerary Save-Load Round-trip
  it("should preserve location data in round-trip", async () => {
    await fc.assert(
      fc.asyncProperty(itineraryArbitrary, async (originalItinerary) => {
        const { id, created_at, updated_at, ...itineraryToSave } =
          originalItinerary;

        const savedId = fc.sample(fc.uuid(), 1)[0];
        const savedCreatedAt = new Date().toISOString();
        const savedUpdatedAt = new Date().toISOString();

        // Mock save
        const mockSaveFrom = vi.fn(() => ({
          insert: vi.fn().mockReturnThis(),
          select: vi.fn().mockReturnThis(),
          single: vi.fn().mockResolvedValue({
            data: {
              id: savedId,
              user_id: itineraryToSave.user_id,
              title: itineraryToSave.title,
              destination: itineraryToSave.destination,
              start_date: itineraryToSave.start_date,
              end_date: itineraryToSave.end_date,
              data: {
                days: itineraryToSave.days,
                shared_with: itineraryToSave.shared_with,
              },
              created_at: savedCreatedAt,
              updated_at: savedUpdatedAt,
            },
            error: null,
          }),
        }));

        vi.mocked(supabase.from).mockImplementation(mockSaveFrom as any);
        const saved = await saveItinerary(itineraryToSave);

        // Mock load
        const mockLoadFrom = vi.fn(() => ({
          select: vi.fn().mockReturnThis(),
          eq: vi.fn().mockReturnThis(),
          single: vi.fn().mockResolvedValue({
            data: {
              id: saved.id,
              user_id: saved.user_id,
              title: saved.title,
              destination: saved.destination,
              start_date: saved.start_date,
              end_date: saved.end_date,
              data: {
                days: saved.days,
                shared_with: saved.shared_with,
              },
              created_at: saved.created_at,
              updated_at: saved.updated_at,
            },
            error: null,
          }),
        }));

        vi.mocked(supabase.from).mockImplementation(mockLoadFrom as any);
        const loaded = await loadItinerary(saved.id);

        // Verify all location data is preserved
        loaded.days.forEach((day, dayIndex) => {
          day.activities.forEach((activity, actIndex) => {
            const originalLocation =
              itineraryToSave.days[dayIndex].activities[actIndex].location;

            expect(activity.location.name).toBe(originalLocation.name);
            expect(activity.location.lat).toBe(originalLocation.lat);
            expect(activity.location.lng).toBe(originalLocation.lng);
            expect(activity.location.place_id).toBe(originalLocation.place_id);
          });
        });
      }),
      { numRuns: 100 }
    );
  });
});

describe("Property 24: Itinerary Deletion", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  // Feature: tripai-travel-planner, Property 24: Itinerary Deletion
  it("should permanently remove itinerary from database", async () => {
    await fc.assert(
      fc.asyncProperty(fc.uuid(), async (itineraryId) => {
        // Mock successful deletion
        const mockDeleteFrom = vi.fn(() => ({
          delete: vi.fn().mockReturnThis(),
          eq: vi.fn().mockResolvedValue({
            data: null,
            error: null,
          }),
        }));

        vi.mocked(supabase.from).mockImplementation(mockDeleteFrom as any);

        // Delete the itinerary
        await deleteItinerary(itineraryId);

        // Verify delete was called
        expect(supabase.from).toHaveBeenCalledWith("itineraries");

        // Mock subsequent load attempt (should fail)
        const mockLoadFrom = vi.fn(() => ({
          select: vi.fn().mockReturnThis(),
          eq: vi.fn().mockReturnThis(),
          single: vi.fn().mockResolvedValue({
            data: null,
            error: {
              message: "No rows found",
              code: "PGRST116",
            },
          }),
        }));

        vi.mocked(supabase.from).mockImplementation(mockLoadFrom as any);

        // Attempting to load deleted itinerary should throw
        await expect(loadItinerary(itineraryId)).rejects.toThrow(
          ItineraryNotFoundError
        );
      }),
      { numRuns: 100 }
    );
  });

  // Feature: tripai-travel-planner, Property 24: Itinerary Deletion
  it("should throw ItineraryNotFoundError when deleting non-existent itinerary", async () => {
    await fc.assert(
      fc.asyncProperty(fc.uuid(), async (nonExistentId) => {
        // Mock not found error on delete
        const mockFrom = vi.fn(() => ({
          delete: vi.fn().mockReturnThis(),
          eq: vi.fn().mockResolvedValue({
            data: null,
            error: {
              message: "No rows found",
              code: "PGRST116",
            },
          }),
        }));

        vi.mocked(supabase.from).mockImplementation(mockFrom as any);

        // Attempt to delete should throw
        await expect(deleteItinerary(nonExistentId)).rejects.toThrow(
          ItineraryNotFoundError
        );
      }),
      { numRuns: 100 }
    );
  });

  // Feature: tripai-travel-planner, Property 24: Itinerary Deletion
  it("should not return deleted itinerary in list", async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.array(itineraryArbitrary, { minLength: 2, maxLength: 5 }),
        fc.integer({ min: 0, max: 4 }),
        async (itineraries, deleteIndex) => {
          // Ensure deleteIndex is valid
          fc.pre(deleteIndex < itineraries.length);

          const itineraryToDelete = itineraries[deleteIndex];

          // Mock successful deletion
          const mockDeleteFrom = vi.fn(() => ({
            delete: vi.fn().mockReturnThis(),
            eq: vi.fn().mockResolvedValue({
              data: null,
              error: null,
            }),
          }));

          vi.mocked(supabase.from).mockImplementation(mockDeleteFrom as any);

          // Delete one itinerary
          await deleteItinerary(itineraryToDelete.id);

          // Mock list operation (should not include deleted)
          const remainingItineraries = itineraries.filter(
            (_, i) => i !== deleteIndex
          );
          const mockListFrom = vi.fn(() => ({
            select: vi.fn().mockReturnThis(),
            order: vi.fn().mockResolvedValue({
              data: remainingItineraries.map((it) => ({
                id: it.id,
                title: it.title,
                destination: it.destination,
                start_date: it.start_date,
                end_date: it.end_date,
                created_at: it.created_at,
                updated_at: it.updated_at,
              })),
              error: null,
            }),
          }));

          vi.mocked(supabase.from).mockImplementation(mockListFrom as any);

          // List itineraries
          const list = await listUserItineraries();

          // Verify deleted itinerary is not in list
          expect(
            list.find((it) => it.id === itineraryToDelete.id)
          ).toBeUndefined();
          expect(list.length).toBe(remainingItineraries.length);
        }
      ),
      { numRuns: 100 }
    );
  });
});
