import type { Itinerary } from '@/types/itinerary';

export const loadItinerary = async (id: string): Promise<Itinerary> => {
    // Simulate loading
    await new Promise(resolve => setTimeout(resolve, 1000));

    // Mock itinerary data
    const mockItinerary: Itinerary = {
        id: id,
        user_id: 'mock-user-id',
        title: 'Tokyo Adventure',
        destination: 'Tokyo, Japan',
        start_date: '2026-03-01',
        end_date: '2026-03-05',
        days: [
            {
                day_number: 1,
                date: '2026-03-01',
                activities: [
                    {
                        id: crypto.randomUUID(),
                        time: '09:00',
                        title: 'Arrive at Narita Airport',
                        description: 'Take the Narita Express to Tokyo Station',
                        location: {
                            name: 'Narita International Airport',
                            lat: 35.7647,
                            lng: 140.3864,
                        },
                        duration_minutes: 120,
                        order: 0,
                    },
                    {
                        id: crypto.randomUUID(),
                        time: '14:00',
                        title: 'Check into Hotel',
                        description: 'Drop off luggage and freshen up',
                        location: {
                            name: 'Shibuya Hotel',
                            lat: 35.6595,
                            lng: 139.7004,
                        },
                        duration_minutes: 60,
                        order: 1,
                    },
                    {
                        id: crypto.randomUUID(),
                        time: '16:00',
                        title: 'Explore Shibuya Crossing',
                        description: 'Visit the famous scramble crossing and surrounding area',
                        location: {
                            name: 'Shibuya Crossing',
                            lat: 35.6595,
                            lng: 139.7004,
                        },
                        duration_minutes: 120,
                        order: 2,
                    },
                    {
                        id: crypto.randomUUID(),
                        time: '19:00',
                        title: 'Dinner at Ichiran Ramen',
                        description: 'Try authentic tonkotsu ramen at this famous chain',
                        location: {
                            name: 'Ichiran Shibuya',
                            lat: 35.6627,
                            lng: 139.6989,
                        },
                        duration_minutes: 90,
                        order: 3,
                    },
                ],
            },
            {
                day_number: 2,
                date: '2026-03-02',
                activities: [
                    {
                        id: crypto.randomUUID(),
                        time: '08:00',
                        title: 'Tsukiji Outer Market',
                        description: 'Fresh sushi breakfast and explore the market',
                        location: {
                            name: 'Tsukiji Outer Market',
                            lat: 35.6654,
                            lng: 139.7707,
                        },
                        duration_minutes: 120,
                        order: 0,
                    },
                    {
                        id: crypto.randomUUID(),
                        time: '11:00',
                        title: 'Senso-ji Temple',
                        description: 'Visit Tokyo\'s oldest temple in Asakusa',
                        location: {
                            name: 'Senso-ji Temple',
                            lat: 35.7148,
                            lng: 139.7967,
                        },
                        duration_minutes: 90,
                        order: 1,
                    },
                    {
                        id: crypto.randomUUID(),
                        time: '13:00',
                        title: 'Lunch at Nakamise Shopping Street',
                        description: 'Try traditional Japanese street food',
                        location: {
                            name: 'Nakamise Shopping Street',
                            lat: 35.7119,
                            lng: 139.7965,
                        },
                        duration_minutes: 60,
                        order: 2,
                    },
                    {
                        id: crypto.randomUUID(),
                        time: '15:00',
                        title: 'Tokyo Skytree',
                        description: 'Panoramic views from the observation deck',
                        location: {
                            name: 'Tokyo Skytree',
                            lat: 35.7101,
                            lng: 139.8107,
                        },
                        duration_minutes: 120,
                        order: 3,
                    },
                    {
                        id: crypto.randomUUID(),
                        time: '18:30',
                        title: 'Dinner in Akihabara',
                        description: 'Explore the electric town and have dinner at a themed cafe',
                        location: {
                            name: 'Akihabara Electric Town',
                            lat: 35.7022,
                            lng: 139.7744,
                        },
                        duration_minutes: 150,
                        order: 4,
                    },
                ],
            },
            {
                day_number: 3,
                date: '2026-03-03',
                activities: [
                    {
                        id: crypto.randomUUID(),
                        time: '09:00',
                        title: 'Meiji Shrine',
                        description: 'Peaceful shrine surrounded by forest in the heart of Tokyo',
                        location: {
                            name: 'Meiji Shrine',
                            lat: 35.6764,
                            lng: 139.6993,
                        },
                        duration_minutes: 90,
                        order: 0,
                    },
                    {
                        id: crypto.randomUUID(),
                        time: '11:00',
                        title: 'Harajuku Takeshita Street',
                        description: 'Explore trendy fashion and unique shops',
                        location: {
                            name: 'Takeshita Street',
                            lat: 35.6702,
                            lng: 139.7037,
                        },
                        duration_minutes: 120,
                        order: 1,
                    },
                    {
                        id: crypto.randomUUID(),
                        time: '13:30',
                        title: 'Lunch at Omotesando',
                        description: 'Upscale dining in Tokyo\'s Champs-Élysées',
                        location: {
                            name: 'Omotesando',
                            lat: 35.6652,
                            lng: 139.7125,
                        },
                        duration_minutes: 90,
                        order: 2,
                    },
                    {
                        id: crypto.randomUUID(),
                        time: '16:00',
                        title: 'teamLab Borderless',
                        description: 'Immersive digital art museum experience',
                        location: {
                            name: 'teamLab Borderless',
                            lat: 35.6251,
                            lng: 139.7753,
                        },
                        duration_minutes: 150,
                        order: 3,
                    },
                    {
                        id: crypto.randomUUID(),
                        time: '19:30',
                        title: 'Dinner at Odaiba',
                        description: 'Waterfront dining with Rainbow Bridge views',
                        location: {
                            name: 'Odaiba Seaside Park',
                            lat: 35.6297,
                            lng: 139.7744,
                        },
                        duration_minutes: 120,
                        order: 4,
                    },
                ],
            },
            {
                day_number: 4,
                date: '2026-03-04',
                activities: [
                    {
                        id: crypto.randomUUID(),
                        time: '08:00',
                        title: 'Day Trip to Mount Fuji',
                        description: 'Scenic bus tour to Japan\'s iconic mountain',
                        location: {
                            name: 'Mount Fuji 5th Station',
                            lat: 35.3606,
                            lng: 138.7274,
                        },
                        duration_minutes: 180,
                        order: 0,
                    },
                    {
                        id: crypto.randomUUID(),
                        time: '12:00',
                        title: 'Lunch at Kawaguchiko',
                        description: 'Local cuisine with lake and mountain views',
                        location: {
                            name: 'Lake Kawaguchi',
                            lat: 35.5131,
                            lng: 138.7634,
                        },
                        duration_minutes: 90,
                        order: 1,
                    },
                    {
                        id: crypto.randomUUID(),
                        time: '14:00',
                        title: 'Oshino Hakkai',
                        description: 'Eight sacred ponds with crystal clear spring water',
                        location: {
                            name: 'Oshino Hakkai',
                            lat: 35.4564,
                            lng: 138.8419,
                        },
                        duration_minutes: 90,
                        order: 2,
                    },
                    {
                        id: crypto.randomUUID(),
                        time: '16:30',
                        title: 'Return to Tokyo',
                        description: 'Bus ride back to the city',
                        location: {
                            name: 'Shinjuku Station',
                            lat: 35.6896,
                            lng: 139.7006,
                        },
                        duration_minutes: 150,
                        order: 3,
                    },
                    {
                        id: crypto.randomUUID(),
                        time: '20:00',
                        title: 'Dinner at Shinjuku',
                        description: 'Explore the vibrant nightlife and dining scene',
                        location: {
                            name: 'Omoide Yokocho',
                            lat: 35.6938,
                            lng: 139.7009,
                        },
                        duration_minutes: 120,
                        order: 4,
                    },
                ],
            },
            {
                day_number: 5,
                date: '2026-03-05',
                activities: [
                    {
                        id: crypto.randomUUID(),
                        time: '09:00',
                        title: 'Imperial Palace East Gardens',
                        description: 'Stroll through the beautiful palace gardens',
                        location: {
                            name: 'Imperial Palace East Gardens',
                            lat: 35.6852,
                            lng: 139.7528,
                        },
                        duration_minutes: 120,
                        order: 0,
                    },
                    {
                        id: crypto.randomUUID(),
                        time: '11:30',
                        title: 'Ginza Shopping District',
                        description: 'Luxury shopping and window browsing',
                        location: {
                            name: 'Ginza',
                            lat: 35.6717,
                            lng: 139.7650,
                        },
                        duration_minutes: 150,
                        order: 1,
                    },
                    {
                        id: crypto.randomUUID(),
                        time: '14:30',
                        title: 'Last Minute Souvenir Shopping',
                        description: 'Pick up gifts and souvenirs at Tokyo Station',
                        location: {
                            name: 'Tokyo Station',
                            lat: 35.6812,
                            lng: 139.7671,
                        },
                        duration_minutes: 90,
                        order: 2,
                    },
                    {
                        id: crypto.randomUUID(),
                        time: '16:30',
                        title: 'Check out from Hotel',
                        description: 'Collect luggage and head to the airport',
                        location: {
                            name: 'Shibuya Hotel',
                            lat: 35.6595,
                            lng: 139.7004,
                        },
                        duration_minutes: 60,
                        order: 3,
                    },
                    {
                        id: crypto.randomUUID(),
                        time: '18:00',
                        title: 'Depart from Narita Airport',
                        description: 'Check-in and departure',
                        location: {
                            name: 'Narita International Airport',
                            lat: 35.7647,
                            lng: 140.3864,
                        },
                        duration_minutes: 180,
                        order: 4,
                    },
                ],
            },
        ],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        shared_with: [],
    };

    return mockItinerary;
};
